chore: separate build and test, set threshold for test (#143)
* chore: separate build and test, set threshold for test

* chore: exclude e2e dir in coverage for future integration

* chore: fix decimal point issue by flooring

diff --git a/.github/workflows/go.yml b/.github/workflows/go.yml
--- a/.github/workflows/go.yml
+++ b/.github/workflows/go.yml
@@ -23,5 +23,34 @@ jobs:
       - name: Build
         run: make build
 
+  test-coverage:
+    runs-on: ubuntu-latest
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Set up Go
+        uses: actions/setup-go@v4
+        with:
+          go-version: "1.23"
+
       - name: Test
-        run: go test -coverpkg=./... ./... -v && go test ./... -coverprofile cover.out && go tool cover -func=cover.out
+        run: |
+          go test -coverpkg=$(go list ./... | grep -v "/test/e2e") $(go list ./... | grep -v "/test/e2e") -v
+          go test $(go list ./... | grep -v "/test/e2e") -coverprofile=cover.out
+          go tool cover -func=cover.out
+
+          coverage=$(go tool cover -func=cover.out | awk '/total:/ {print $3}' | sed 's/%//' | awk '{print $1}')
+          threshold=80
+
+          if [[ -z "$coverage" ]]; then
+          echo "Error:Could not extract coverage percentage."
+          exit 1
+          fi
+
+          if (( $(echo $(printf "%.0f" "$coverage") ) < $threshold )); then
+          echo "Error:Coverage is below threshold ($coverage% < $threshold%)"
+          exit 1
+
+          else
+          echo "Coverage is $coverage%, which meets the threshold ($threshold%)"
+          fi
